### ISSUE TITLE
Error when getting in to backoffice for first time

### ISSUE THREAD

**Issue by mvbressler** [outfielddigital/konstrukt-demo#1]
Hi, I´m getting an error with text: "An item with the same key has already been added. Key: repositories"

Exception Details
System.ArgumentException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: An item with the same key has already been added. Key: repositories

Umbraco 9.2
Konstrukt 1.1.0-alpha0001

**Comment by mattbrailsford** [comment]
This is an intermittent bug we are seeing that is usually resolved by just restarting the app. We’ll investigate it further though 👍🏻

**Comment by mattbrailsford** [comment]
@mvbressler I've made an update to the core package and updated the demo which now checks before adding sections etc to ensure they haven't already been registered. This should resolve this issue.

Feel free to re-open this issue if this turns out to not be the case.
